import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const root = join(import.meta.dirname, '..');

interface Tokens {
  colors: {
    violet: string;
    violetBright: string;
    violetDeep: string;
    pink: string;
    pinkBright: string;
    amber: string;
    amberBright: string;
    ink: string;
  };
  fonts: {
    display: string;
    body: string;
  };
}

function readTokens(): Tokens {
  return JSON.parse(readFileSync(join(root, 'design/tokens.json'), 'utf-8')) as Tokens;
}

function hexToRgba(hex: string, alpha: number): string {
  const value = hex.replace('#', '');
  const r = parseInt(value.slice(0, 2), 16);
  const g = parseInt(value.slice(2, 4), 16);
  const b = parseInt(value.slice(4, 6), 16);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

function buildAppCss(tokens: Tokens): string {
  const { colors, fonts } = tokens;
  return `/* GENERATED by scripts/generate-tokens.ts from design/tokens.json — do not hand-edit.
   Overrides the accent/font tokens defined in tokens.css with the shared brand
   identity introduced by the install site redesign, so the app and the site
   stay visually one product instead of drifting into two separate palettes. */
:root {
  --color-accent: ${colors.violet};
  --color-accent-hover: ${colors.violetBright};
  --color-accent-pressed: ${colors.violetDeep};
  --color-accent-muted: ${hexToRgba(colors.violet, 0.12)};

  --brand-violet: ${colors.violet};
  --brand-pink: ${colors.pink};
  --brand-amber: ${colors.amber};
  --brand-grad: linear-gradient(120deg, ${colors.violet} 0%, ${colors.pink} 55%, ${colors.amber} 100%);
  --font-display: ${fonts.display};
}
`;
}

function main(): void {
  const tokens = readTokens();
  const appCssPath = join(root, 'client/src/styles/brand.css');
  writeFileSync(appCssPath, buildAppCss(tokens), 'utf-8');
  console.log('Generated client/src/styles/brand.css from design/tokens.json');
}

main();
