// Role: regenerate the README's version-dependent sections from package.json +
// CHANGELOG.md, so they can never drift again.
//
// The README's "What's New" was hand-written and sat at v1.0.1 while the app
// shipped 1.2.0. Session 3's version-sync work only ever covered docs/ — the
// README was outside it entirely. This closes that gap using the same
// changelog source the site renders from, and runs in the same workflow that
// commits the regenerated site back to main.
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { entryForVersion, parseChangelog, readProjectFile, repoRoot, resolveVersion } from './lib/changelog';

const README_PATH = join(repoRoot, 'README.md');

const BEGIN = '<!-- BEGIN:WHATS-NEW -->';
const END = '<!-- END:WHATS-NEW -->';

function renderWhatsNew(version: string): string {
  const entries = parseChangelog(readProjectFile('CHANGELOG.md'));
  const entry = entryForVersion(entries, version);

  if (!entry) {
    return `## What's New in v${version}\n\nSee [CHANGELOG.md](CHANGELOG.md).`;
  }

  const parts: string[] = [`## What's New in v${entry.version}`, ''];

  for (const section of entry.sections) {
    if (section.title) parts.push(`**${section.title}**`, '');
    for (const item of section.items) parts.push(`- ${item}`);
    parts.push('');
  }

  parts.push(`[Full changelog](CHANGELOG.md) · [All releases](https://github.com/Isaac-Onyango-Dev/StreamDock/releases)`);
  return parts.join('\n');
}

function main(): void {
  const version = resolveVersion();
  const readme = readFileSync(README_PATH, 'utf-8');

  const beginIndex = readme.indexOf(BEGIN);
  const endIndex = readme.indexOf(END);
  if (beginIndex === -1 || endIndex === -1 || endIndex < beginIndex) {
    throw new Error(
      `README.md is missing the ${BEGIN} / ${END} markers — add them around the ` +
      "\"What's New\" section so this script knows what to replace.",
    );
  }

  const generated = [
    BEGIN,
    '<!-- Generated by scripts/sync-readme.ts from CHANGELOG.md — do not edit by hand. -->',
    '',
    renderWhatsNew(version),
    '',
    END,
  ].join('\n');

  const next = readme.slice(0, beginIndex) + generated + readme.slice(endIndex + END.length);

  if (next === readme) {
    console.log(`README.md already in sync with v${version}`);
    return;
  }

  writeFileSync(README_PATH, next, 'utf-8');
  console.log(`Synced README.md to v${version}`);
}

main();
